name: Haskell CI/CD

on:
  create:
    tags:
      - "v*.*.*"
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Set environment variable
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
    - name: Test enviornment variable
      run: echo ${{ env.RELEASE_VERSION }}

    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-global-
          
    - uses: actions/cache@v3
      name: Cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-

    - name: Run tests
      run: 
        stack test
          
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/interactive-calculator:$${{ env.RELEASE_VERSION }}
      
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
