name: Haskell CI/CD

on:
  push:
    branches:
      - main 
      - CD-patch
    create:
      tags:
        - "v*.*.*"
      
jobs:
  build:
    runs-on: haskell:8.6.5 
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-global-
          
    - uses: actions/cache@v3
      name: Cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-
          
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/haskell-calculator:1.0.0
      
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
    - name: Run tests
      run: stack test
